### ISSUE TITLE
Скласти додаткові інформаційні блоки

### ISSUE THREAD

**Issue by Khrapal-Max** [Khrapal-Max/homepage#4]
Можна зробити резюме менш формальним, додавши додаткові блоки, які містять корисну інформацію, але подають її в "розважальній" формі. Наприклад, що подобається і не подобається, сильні і слабкі сторони, перелік навиків чи хобі, інфографіка або ж інтерактивні модулі, тощо. Варто написати контент такого блоку раніше, ніж починати верстку, бо його розміри впливатимуть на розміщення елементів на сторінці.

**Comment by Westsvarg** [comment]
<div class="tech-skills-container">
                            <h3 class="tech-skills-title">Tech Skills</h3>
                            <ul>
                                <li class="tech-skills-item">
                                    <span class="tech-skills-text">С#</span>
                                </li>
                                <li class="tech-skills-item">
                                    <span class="tech-skills-text">.NET</span>
                                </li>
                                <li class="tech-skills-item">
                                    <span class="tech-skills-text">OOP</span>
                                </li>
                                <li class="tech-skills-item">
                                    <span class="tech-skills-text">SOLID</span>
                                </li>
                                <li class="tech-skills-item">
                                    <span class="tech-skills-text">Asp .Net Core MVC</span>
                                </li>
                                <li class="tech-skills-item">
                                    <span class="tech-skills-text">EF Core</span>
                                </li>
                                <li class="tech-skills-item">
                                    <span class="tech-skills-text">SQL</span>
                                </li>
                                <li class="tech-skills-item">
                                    <span class="tech-skills-text">Unity</span>
                                </li>
                            </ul>
                        </div>
                        <div class="soft-skills-container">
                            <h3 class="soft-skills-title">Soft Skills</h3>
                            <ul>
                                <li class="soft-skills-item">
                                    <span class="soft-skills-text">The presence of leadership and management skills</span>
                                </li>
                                <li class="soft-skills-item">
                                    <span class="soft-skills-text">Setting goals, planning and managing time</span>
                                </li>
                                <li class="soft-skills-item">
                                    <span class="soft-skills-text">Responsibility for setting team tasks and achieving results</span>
                                </li>
                                <li class="soft-skills-item">
                                    <span class="soft-skills-text">Ability to predict the emergence of problems thereby working ahead of the curve</span>
                                </li>
                            </ul>
                        </div>
                        <div class="soft-skills-container">
                            <h3 class="soft-skills-title">Language:</h3>
                            <ul>
                                <li class="soft-skills-item">
                                    <span class="soft-skills-text">English - Pre-Intermediate.</span>
                                </li>
                            </ul>
                        </div>
