### ISSUE TITLE
Скласти таймлайн

### ISSUE THREAD

**Issue by Khrapal-Max** [Khrapal-Max/homepage#5]
Скласти список всіх (важливих) життєвих подій, визначних дат, досягнень, періодів, що дали приємний і неприємний досвід, тощо. В цьому конкретному випадку довгих списків не буває, натомість бувають погано згорнуті, тому пакуємо сюди все підряд, а про "лишні" події можна буде промовчати пізніше. Список повинен бути систематизованим і посортованим в такий спосіб, щоб читач швидко зрозумів "паттерн" і міг легко орієнтуватись в просторі і часі цього резюме.

**Comment by Westsvarg** [comment]
<section>
                        <div class="experience-container">
                            <div>
                                <h3 class="about-me-title">Work Experience</h3>
                                
                                <div>
                                    <h3 class="profession-title">
                                        Head of Customer Care
                                    </h3>
                                    <h3>
                                        <a class="professional-company" href="https://allo.ua/">LLC Allo</a>
                                    </h3>
                                    <span class="professional-time">
                                        Mar 2018 – Aug 2020
                                        <span class="profession-divider">|</span> Ukraine
                                    </span>
                                    <ul class="professional-duties">
                                        <li class="professional-duties-item">
                                            Business process optimization.
                                        </li>
                                        <li class="professional-duties-item">
                                            Drafting legal services agreements (SLA).
                                        </li>
                                        <li class="professional-duties-item">
                                            Organization of logistic schemes.
                                        </li>
                                        <li class="professional-duties-item">
                                            Quality control of service in the company.
                                        </li>
                                        <li class="professional-duties-item">
                                            Development of a service development strategy.
                                        </li>
                                        <li class="professional-duties-item">
                                            Automation of service processes in the company's software.
                                        </li>
                                        <li class="professional-duties-item">
                                            Development of software integration projects with partner databases.
                                        </li>
                                        <li class="professional-duties-item">
                                            Development and implementation of Service Desk for service processes.
                                        </li>
                                    </ul>
                                </div>
                                
                                <div>
                                    <h3 class="profession-title">
                                        Head of the regional service customer
                                    </h3>
                                    <h3>
                                        <a class="professional-company" href="https://www.foxtrot.com.ua/">Group of companies Foxtrot</a>
                                    </h3>
                                    <span class="professional-time">
                                        Aug 2011 – Dec 2017
                                        <span class="profession-divider">|</span> Ukraine
                                    </span>
                                    <ul class="professional-duties">
                                        <li class="professional-duties-item">
                                            Preparing business plans.
                                        </li>
                                        <li class="professional-duties-item">
                                            Planning budget.
                                        </li>
                                        <li class="professional-duties-item">
                                            Analyzing data sets.
                                        </li>
                                        <li class="professional-duties-item">
                                            Business correspondence.
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </section>
                    
                    <section>
                        <div class="education-container">
                            <div>
                                <div>
                                    <h3 class="about-me-title">Education</h3>
                                </div>
                                <p class="education-university">State Higher Education Institution «National Mining University (NMU)»</p>
                                <p class="education-specialty">Specialist in Economics of enterprise <span class="education-time">Jun 2015<span class="education-divider">|</span> Ukraine</span>
                            </div>
                            <div>
                                <div>
                                    <h3 class="about-me-title">Additional Education, Courses</h3>
                                </div>
                                <div>
                                    <p class="education-specialty">Course: C# Online Marathon</p>
                                    <p class="education-ITuniversity">Softserve (IT Academy) <span class="education-time">October 2020 – December 2020<span class="education-divider">|</span> Ukraine</span>
                                </div>
                                <div>
                                    <p class="education-specialty">Course: Elementary C#</p>
                                    <p class="education-ITuniversity">Hillel (IT School) Dnipro  <span class="education-time">May 2020 – September 2020<span class="education-divider">|</span> Ukraine</span>
                                </div>
                                <div>
                                    <p class="education-specialty">Course: OBJECT-ORIENTED PROGRAMMING IN C#</p>
                                    <p class="education-ITuniversity">Softserve (IT Academy) <span class="education-time">Jul 2020 – Aug 2020<span class="education-divider">|</span> Ukraine</span>
                                </div>
                                <div>
                                    <p class="education-specialty">Course: Unity</p>
                                    <p class="education-ITuniversity">Level Up (IT School) Dnipro <span class="education-time">Jun 2017 – Nov 2017<span class="education-divider">|</span> Ukraine</span>
                                </div>
                                <div>
                                    <p class="education-specialty">Course: Introduction C#</p>
                                    <p class="education-ITuniversity">Hillel (IT School) Dnipro <span class="education-time">Apr 2017 – Jun 2017<span class="education-divider">|</span> Ukraine</span>
                                </div>
                            </div>
                        </div>
                    </section>
