### ISSUE TITLE
Скласти блок контактної інформації

### ISSUE THREAD

**Issue by Khrapal-Max** [Khrapal-Max/homepage#6]
Посилання на соцмережі (Facebook чи Instagram, тощо), номер телефону чи адреса електронної скриньки, тощо. Може не всі лінки в світі, а тільки ті, що дійсно доречні.

**Comment by Westsvarg** [comment]
<div class="contacts-container">
                            <h3 class="contacts-title">Contacts:</h3>
                            <div>
                                <span class="contacts-link-type">Phone number:</span>
                                <a class="contacts-link" href="tel:380668756458">+38 066 875 64 58</a>
                            </div>
                            <div>
                                <span class="contacts-link-type">Email:</span>
                                <a class="contacts-link" href="mailto:khrapal_m_g@outlook.com"> Khrapal_M_G@outlook.com</a>
                            </div>
                            <div>
                                <span class="contacts-link-type">Linkedin:</span>
                                <a class="contacts-link" href="https://www.linkedin.com/in/maksym-khrapal-2867bba9"> Maksym Khrapal</a>
                            </div>
                            <div>
                                <span class="contacts-link-type">Github:</span>
                                <a class="contacts-link" href="https://github.com/Khrapal-Max">  Maksym Khrapal</a>
                            </div>
                        </div>
