### ISSUE TITLE
Скласти інтро

### ISSUE THREAD

**Issue by Khrapal-Max** [Khrapal-Max/homepage#7]
Скласти інтро (вступ), де в 2-4 реченнях описати, що замовник робить, що подобається робити, що хочеться робити краще, що важливо робити, тощо.

**Comment by Westsvarg** [comment]
<section>
                        <div class="experience-container">
                            <h3 class="about-me-title">Resume</h3>
                            <p> <span class="profession-title"></span> Hello. I'm actively studying IT technology in order to build accurate, flexible, fast and simple business models and IT solutions.</p>
                        </div>
                    </section>
